In [1]:
import torch

/home/liyichong/.conda/envs/RD/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model_dir = './model_param/4_47/'

In [3]:
torch.load(model_dir + 'backbone.pth', map_location=lambda storage, loc: storage)

OrderedDict([('gin_block_0.GIN.eps', tensor([0.])),
             ('gin_block_0.GIN.nn.0.weight',
              tensor([[-0.0162,  0.0544,  0.0219,  ...,  0.0914, -0.0204,  0.0858],
                      [ 0.0066,  0.0625, -0.0741,  ..., -0.0026,  0.0349,  0.1194],
                      [-0.0895,  0.1282,  0.0574,  ..., -0.1304, -0.0489, -0.0752],
                      ...,
                      [-0.0501, -0.0806, -0.0161,  ..., -0.0328,  0.0368,  0.0368],
                      [-0.0467, -0.0109,  0.0846,  ...,  0.0989,  0.0493,  0.0398],
                      [-0.1250,  0.0394,  0.0845,  ...,  0.1118, -0.0165, -0.1327]])),
             ('gin_block_0.GIN.nn.0.bias',
              tensor([ 8.1994e-05, -1.3344e-05, -5.2165e-05, -4.1431e-07,  1.8820e-04,
                      -3.0457e-06, -2.6373e-04, -1.1748e-04,  1.5002e-04,  3.8521e-05,
                       1.2933e-04, -1.3740e-05, -6.8112e-05,  3.3036e-06,  7.2804e-06,
                       1.7065e-05, -7.8596e-05,  6.6099e-05, -1.4

In [4]:
model_weight = torch.load(model_dir + 'backbone.pth', map_location=lambda storage, loc: storage)

In [5]:
model_weight

OrderedDict([('gin_block_0.GIN.eps', tensor([0.])),
             ('gin_block_0.GIN.nn.0.weight',
              tensor([[-0.0162,  0.0544,  0.0219,  ...,  0.0914, -0.0204,  0.0858],
                      [ 0.0066,  0.0625, -0.0741,  ..., -0.0026,  0.0349,  0.1194],
                      [-0.0895,  0.1282,  0.0574,  ..., -0.1304, -0.0489, -0.0752],
                      ...,
                      [-0.0501, -0.0806, -0.0161,  ..., -0.0328,  0.0368,  0.0368],
                      [-0.0467, -0.0109,  0.0846,  ...,  0.0989,  0.0493,  0.0398],
                      [-0.1250,  0.0394,  0.0845,  ...,  0.1118, -0.0165, -0.1327]])),
             ('gin_block_0.GIN.nn.0.bias',
              tensor([ 8.1994e-05, -1.3344e-05, -5.2165e-05, -4.1431e-07,  1.8820e-04,
                      -3.0457e-06, -2.6373e-04, -1.1748e-04,  1.5002e-04,  3.8521e-05,
                       1.2933e-04, -1.3740e-05, -6.8112e-05,  3.3036e-06,  7.2804e-06,
                       1.7065e-05, -7.8596e-05,  6.6099e-05, -1.4